// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-yva38l2j10mIpYxau3Sz1cD6v11ZQ_E',
    appId: '1:333663009463:web:32c080841245927d50ab32',
    messagingSenderId: '333663009463',
    projectId: 'billmate-sl',
    authDomain: 'billmate-sl.firebaseapp.com',
    storageBucket: 'billmate-sl.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5pGqvfk1Bu6oFr14JeQmuaIvO0lrLENE',
    appId: '1:333663009463:android:d98fe8df8caaa32a50ab32',
    messagingSenderId: '333663009463',
    projectId: 'billmate-sl',
    storageBucket: 'billmate-sl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnI1XKuO6qnVy_AXTuK3jEUReM6F68JBs',
    appId: '1:333663009463:ios:77d4148e80f5d0fe50ab32',
    messagingSenderId: '333663009463',
    projectId: 'billmate-sl',
    storageBucket: 'billmate-sl.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnI1XKuO6qnVy_AXTuK3jEUReM6F68JBs',
    appId: '1:333663009463:ios:77d4148e80f5d0fe50ab32',
    messagingSenderId: '333663009463',
    projectId: 'billmate-sl',
    storageBucket: 'billmate-sl.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-yva38l2j10mIpYxau3Sz1cD6v11ZQ_E',
    appId: '1:333663009463:web:9fa780bf0868accf50ab32',
    messagingSenderId: '333663009463',
    projectId: 'billmate-sl',
    authDomain: 'billmate-sl.firebaseapp.com',
    storageBucket: 'billmate-sl.firebasestorage.app',
  );
}
